:green_heart: fix for a problem whici is caused by a rust version.
Caused by:
  the cargo feature `publish-lockfile` requires a nightly version of Cargo, but this is the `stable` channel
after_success
0.02s$ if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    fi

error: no such subcommand: `tarpaulin`